[package]
name = "file_server"
version = "0.1.0"
edition = "2021"

[dependencies]
md5 = "0.7.0"
reqwest = "0.12.12"
serde_json = "1.0.138"
teloxide = { version = "0.13", features = ["macros"] }
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
